"""Add shop_id to products table

Revision ID: 24b2265b4479
Revises: 851df2b5e7b8
Create Date: 2026-07-22 11:50:03.929045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b2265b4479'
down_revision = '851df2b5e7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
