"""Make shop_id NOT NULL

Revision ID: 43763ab2f05f
Revises: 24b2265b4479
Create Date: 2026-07-22 11:59:50.888972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43763ab2f05f'
down_revision = '24b2265b4479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
