"""Add profit tracking and price history to products

Revision ID: aaba1a1a6941
Revises: 5e4534814508
Create Date: 2026-08-27 16:59:15.364922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaba1a1a6941'
down_revision = '5e4534814508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_profit_per_unit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('expected_profit_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_margin_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_history', sa.Text(), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('tax')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('join_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('salary',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_staff_shop_employee', ['shop_id', 'employee_id'])
        batch_op.drop_constraint(batch_op.f('fk_staff_shop_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'shops', ['shop_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_staff_shop_id'), 'shops', ['shop_id'], ['id'])
        batch_op.drop_constraint('uq_staff_shop_employee', type_='unique')
        batch_op.alter_column('salary',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('join_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax', mysql.FLOAT(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('price_history')
        batch_op.drop_column('profit_margin_percentage')
        batch_op.drop_column('expected_profit_total')
        batch_op.drop_column('expected_profit_per_unit')

    # ### end Alembic commands ###
