"""Remove categories and add stock_limit

Revision ID: d566c40bf9e3
Revises: 0e70a4ba24dc
Create Date: 2026-07-18 10:22:05.765491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd566c40bf9e3'
down_revision = '0e70a4ba24dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
